DROP DATABASE comment;
CREATE DATABASE IF NOT EXISTS comment  DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
USE comment;
DROP TABLE IF EXISTS `comment`;
CREATE TABLE `comment` (
  `CommentId` VARCHAR(32) NOT NULL COMMENT '评论ID',
  `HotelId` BIGINT DEFAULT 0 COMMENT '酒店编号',
  `UserName` VARCHAR(255) DEFAULT '' COMMENT '用户名',
  `UserRank` INT(11) DEFAULT 0 COMMENT '用户等级 1.新人点评 2.达人点评 3.专家点评',
  `Content` TEXT COMMENT '评论内容',
  `CommentDateTime` DATETIME DEFAULT NULL COMMENT '评论时间',
  `RoomTypeName` VARCHAR(255) DEFAULT '' COMMENT '入住的房间名称',
  `IsMarrow` INT(11) DEFAULT 0 COMMENT '是否是精品评论 0 不是 1 是',
  `CommentFrom` VARCHAR(32) DEFAULT '' COMMENT '评论来源',
  `CommentScoreTotal` FLOAT DEFAULT 0 COMMENT '总评分',
  `TravelType` INT(11) DEFAULT 0 COMMENT '旅行类型：0 其他类型 1 家庭亲子 2 情侣出行 3 朋友出行 4 商务出差 5 独自旅行',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CommentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '评论表';

DROP TABLE IF EXISTS `reply`;
CREATE TABLE `reply` (
  `CommentId`  VARCHAR(32) NOT NULL COMMENT '评论ID',
  `ReplayId` INT(11) DEFAULT 0 COMMENT '回复ID',
  `Content` TEXT COMMENT '回复内容',
  `CreateTime` DATETIME DEFAULT NULL COMMENT '回复时间',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CommentId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '回复表';

DROP TABLE IF EXISTS  `image`;
CREATE TABLE `image` (
  `imageId`  VARCHAR(32) NOT NULL COMMENT '图片ID',
  `CommentId`  VARCHAR(32) NOT NULL COMMENT '评论ID',
  `LargeImagePath` VARCHAR(255) DEFAULT '' COMMENT '图片路径',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`imageId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '图片表';

DROP TABLE IF EXISTS  `score`;
CREATE TABLE `score` (
  `HotelId` BIGINT NOT NULL COMMENT '酒店编号',
  `TotalScore` FLOAT DEFAULT 0 COMMENT '总评分',
  `FacilityScore` FLOAT DEFAULT 0 COMMENT '设施评分',
  `ServiceScore` FLOAT DEFAULT 0 COMMENT '服务评分',
  `SanitationScore` FLOAT DEFAULT 0 COMMENT '卫生评分',
  `PositionScore` FLOAT DEFAULT 0 COMMENT '位置评分',
  `CostScore` FLOAT DEFAULT 0 COMMENT '性价比评分',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HotelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '五维评分	';

DROP TABLE IF EXISTS  `tag`;
CREATE TABLE `tag` (
  `HotelId` BIGINT NOT NULL COMMENT '酒店编号',
  `TagName` VARCHAR(64) DEFAULT '' COMMENT '标签名字',
  `TagNum` INT(11) DEFAULT 0 COMMENT '标记次数',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HotelId`,`TagName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '标签表	';

DROP TABLE IF EXISTS  `historyHotel`;
CREATE TABLE `historyHotel` (
  `HotelId` BIGINT NOT NULL COMMENT '酒店编号',
  `InsertTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`HotelId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '已获取到的酒店表';

